settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200

  - id: sky0427.dns-dynamic.net
    name: a-p.sky0427.dns-dynamic.net
    url: 'http://a.sky0427.dns-dynamic.net'
    method: GET
    expectStatus: 200    

  - id: pdfa.cloudns.be
    name: a-p.pdfa.cloudns.be
    url: 'http://a.pdfa.cloudns.be'
    method: GET
    expectStatus: 200  

  - id: bic.cloudns.ch
    name: a-p.bic.cloudns.ch
    url: 'http://p.bic.cloudns.ch'
    method: GET
    expectStatus: 200  

  - id: xls.cloudns.be
    name: a-p.xls.cloudns.be
    url: 'http://p.xls.cloudns.be'
    method: GET
    expectStatus: 200

  - id: jpg.cloudns.be
    name: a-b.jpg.cloudns.be
    url: 'http://a.jpg.cloudns.be'
    method: GET
    expectStatus: 200

  - id: jpg.cloudns.ch
    name: a-p.jpg.cloudns.ch
    url: 'http://p.jpg.cloudns.ch'
    method: GET
    expectStatus: 200

  - id: dwg.dns-dynamic.net
    name: a-p.dwg.dns-dynamic.net
    url: 'http://p.dwg.dns-dynamic.net'
    method: GET
    expectStatus: 200

  - id: ipt.dns-dynamic.net
    name: a-p.ipt.dns-dynamic.net
    url: 'http://p.ipt.dns-dynamic.net'
    method: GET
    expectStatus: 200

  - id: rar.cloudns.ch
    name: a-p.rar.cloudns.ch
    url: 'http://p.rar.cloudns.ch'
    method: GET
    expectStatus: 200

  - id: exe.cloudns.be
    name: a-p.exe.cloudns.be
    url: 'http://p.exe.cloudns.be'
    method: GET
    expectStatus: 200

  - id: dwg.cloudns.ch
    name: a-p.dwg.cloudns.ch
    url: 'http://p.dwg.cloudns.ch'
    method: GET
    expectStatus: 200

  - id: e.aab.cloudns.be
    name: e.aab.cloudns.be
    url: 'https://e.aab.cloudns.be/'
    method: GET
    expectStatus: 200

  - id: i.xxl.cloudns.ch
    name: i.xxl.cloudns.ch
    url: 'https://i.xxl.cloudns.ch/'
    method: GET
    expectStatus: 200

  - id: g.xml.cloudns.ch
    name: g.xml.cloudns.ch
    url: 'https://g.xml.cloudns.ch/'
    method: GET
    expectStatus: 200

  - id: m.hoo.cloudns.be
    name: m.hoo.cloudns.be
    url: 'https://m.hoo.cloudns.be/'
    method: GET
    expectStatus: 200

  - id: f.ppm.dns-dynamic.net
    name: f.ppm.dns-dynamic.net
    url: 'https://f.ppm.dns-dynamic.net/'
    method: GET
    expectStatus: 200

  - id: k.ae.cloudns.be
    name: k.ae.cloudns.be
    url: 'https://k.ae.cloudns.be/'
    method: GET
    expectStatus: 200    

  - id: h.af.cloudns.ch
    name: h.af.cloudns.ch
    url: 'https://h.af.cloudns.ch/'
    method: GET
    expectStatus: 200    
    
  - id: 9.ag.cloudns.be
    name: 9.ag.cloudns.be
    url: 'https://9.ag.cloudns.be/'
    method: GET
    expectStatus: 200   

  - id: k.ak47.cloudns.ch
    name: k.ak47.cloudns.ch
    url: 'https://k.ak47.cloudns.ch/'
    method: GET
    expectStatus: 200  

  - id: h.a0u.cloudns.be
    name: h.a0u.cloudns.be
    url: 'https://h.a0u.cloudns.be/'
    method: GET
    expectStatus: 200  

  - id: v.az.dns-dynamic.net
    name: v.az.dns-dynamic.net
    url: 'https://v.az.dns-dynamic.net/'
    method: GET
    expectStatus: 200  

  - id: q.biu.dns-dynamic.net
    name: q.biu.dns-dynamic.net
    url: 'https://q.biu.dns-dynamic.net/'
    method: GET
    expectStatus: 200  

  - id: q.bz.cloudns.ch
    name: q.bz.cloudns.ch（小号）
    url: 'https://q.bz.cloudns.ch/'
    method: GET
    expectStatus: 200  

  - id: q.dm0503.cloudns.be
    name: q.dm0503.cloudns.be(小号)
    url: 'https://q.dm0503.cloudns.be/'
    method: GET
    expectStatus: 200 

  - id: D25
    name: a-v.apk.dns-dynamic.net
    url: 'https://v.apk.dns-dynamic.net/'
    method: GET
    expectStatus: 200 

  - id: D26
    name: a-v.ay.cloudns.ch
    url: 'https://v.ay.cloudns.ch/'
    method: GET
    expectStatus: 200 
