settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://blog.cloudflare.com/'
    method: GET
    expectStatus: 200

  - id: sky0427.dns-dynamic.net
    name: sky0427.dns-dynamic.net
    url: 'http://a.sky0427.dns-dynamic.net'
    method: GET
    expectStatus: 404    

  - id: pdfa.cloudns.be
    name: pdfa.cloudns.be
    url: 'http://a.pdfa.cloudns.be:8090/K3Cloud/html5/SCPIndex.aspx'
    method: GET
    expectStatus: 404  

  - id: bic.cloudns.ch
    name: bic.cloudns.ch
    url: 'http://a.bic.cloudns.ch:8090/K3Cloud/html5/SCPIndex.aspx'
    method: GET
    expectStatus: 404  

  - id: xls.cloudns.be
    name: xls.cloudns.be
    url: 'http://a.xls.cloudns.be:8090/K3Cloud/html5/SCPIndex.aspx'
    method: GET
    expectStatus: 404

  - id: jpg.cloudns.be
    name: jpg.cloudns.be
    url: 'https://a.jpg.cloudns.be:8090/K3Cloud/html5/SCPIndex.aspx'
    method: GET
    expectStatus: 404

  - id: jpg.cloudns.ch
    name: jpg.cloudns.ch
    url: 'http://a.jpg.cloudns.ch:8090/K3Cloud/html5/SCPIndex.aspx'
    method: GET
    expectStatus: 404

  - id: dwg.dns-dynamic.net
    name: dwg.dns-dynamic.net
    url: 'http://a.dwg.dns-dynamic.net:8090/K3Cloud/html5/SCPIndex.aspx'
    method: GET
    expectStatus: 404

  - id: ipt.dns-dynamic.net
    name: ipt.dns-dynamic.net
    url: 'http://a.ipt.dns-dynamic.net:8090/K3Cloud/html5/SCPIndex.aspx'
    method: GET
    expectStatus: 404

  - id: rar.cloudns.ch
    name: rar.cloudns.ch
    url: 'http://a.rar.cloudns.ch:8090/K3Cloud/html5/SCPIndex.aspx'
    method: GET
    expectStatus: 404

  - id: exe.cloudns.be
    name: exe.cloudns.be
    url: 'http://a.exe.cloudns.be:8090/K3Cloud/html5/SCPIndex.aspx'
    method: GET
    expectStatus: 404

  - id: dwg.cloudns.ch
    name: dwg.cloudns.ch
    url: 'http://a.dwg.cloudns.ch:8090/K3Cloud/html5/SCPIndex.aspx'
    method: GET
    expectStatus: 404
